version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 5s

  migrate:
    build:
      context: .
      target: production
    image: cv/chatbot-api:local
    env_file:
      - .env
    volumes:
      - ./:/cv
    working_dir: /cv
    depends_on:
      postgres:
        condition: service_healthy
    command: ["sh", "-lc", "alembic upgrade head"]
    restart: "no"

  api:
    build:
      context: .
      target: development
    image: cv/chatbot-api:local
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      PORT: ${PORT:-8000}
    volumes:
      - ./:/cv
      - hf_cache:/root/.cache/huggingface
    working_dir: /cv
    depends_on:
      migrate:
        condition: service_completed_successfully
    command: ["sh", "-lc", "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000} --reload"]
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 5s
      timeout: 2s
      retries: 10


  front:
    build:
      context: ./front
    image: cv/chatbot-front:local
    ports:
      - "5173:5173"
    volumes:
      - ./front:/front
      - front_node_modules:/front/node_modules
    depends_on:
      api:
        condition: service_healthy

  generator:
    build:
      context: .
      target: generation
    image: cv/chatbot-generator:local
    env_file:
      - .env
    volumes:
      - ./:/cv
    working_dir: /cv
    command: ["sh", "-lc", "python -m cv_generation.generate_data --n 30"]
    restart: "no"

  rag_index:
    build:
      context: .
      target: rag
    image: cv/chatbot-rag:local
    env_file:
      - .env
    volumes:
      - ./:/cv
      - hf_cache:/root/.cache/huggingface
    working_dir: /cv
    command: ["sh", "-lc", "python -m rag.rag_cli.build_index --pdf_dir cv_generation/data/cvs --out_dir rag_store"]
    restart: "no"
  
  rag_search:
    build:
      context: .
      target: rag
    image: cv/chatbot-rag:local
    env_file:
      - .env
    volumes:
      - ./:/cv
      - hf_cache:/root/.cache/huggingface
    working_dir: /cv
    command: ["sh", "-lc", "python -m rag.rag_cli.search --index_dir rag_store --query 'Who has Python experience?'"]
    restart: "no"

volumes:
  postgres_data:
  front_node_modules:
  hf_cache: